// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://luzjvgswescfdxhyvqkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1emp2Z3N3ZXNjZmR4aHl2cWtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMDI1NTYsImV4cCI6MjA2Nzg3ODU1Nn0.RyOx7KvBFfqs6dQHCA2DpErDK8SrnvWnmr6MoNP8J2s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});